### ISSUE TITLE
Edits missing from SPARQL

### ISSUE THREAD

**Issue by madewild** [ec-doris/EuKnowledgeGraph#117]
This query gives projects in Portugal with no Maltese label: https://query.linkedopendata.eu/#select%20%2a%20where%20%7B%0A%20%20%3Fs%20wdt%3AP35%20wd%3AQ9934%20.%0A%20%20%3Fs%20wdt%3AP32%20wd%3AQ18%20.%0A%20%20FILTER%20NOT%20EXISTS%20%7B%3Fs%20rdfs%3Alabel%20%3Flabel%20FILTER%28lang%28%3Flabel%29%3D%27mt%27%29%7D%0A%7D%20LIMIT%2010

But actually the first result in the list https://linkedopendata.eu/wiki/Item:Q2860226 HAS a Maltese label! So it seems the updater has not been catching up with all the translations... This one was on 29 July (see https://linkedopendata.eu/w/index.php?title=Item:Q2860226&action=history), maybe we need to re-run it around that date. How can we do this inside the cluster?

**Comment by D063520** [comment]
To run this inside the cluster you have to:
1) go to the updater machine in prod
2) cd lib
3) java -cp wikidata-query-tools-0.3.40-jar-with-dependencies.jar org.wikidata.query.rdf.tool.Update  --wikibaseHost https://linkedopendata.eu/ --wikibaseUrl https://linkedopendata.eu/ --conceptUri https:/inkedopendata.eu/ --wikibaseScheme https --entityNamespaces 120,122 --start 2022-06-01T12:50:19Z --sparqlUrl http://wikibase-wdqs-service/bigdata/namespace/wdq/sparql

I run it now from the 01/01/2022. The above problem is fixed. The query in fact times out because he cannot find anymore in the timeout period a matching result
